# Generated by Django 2.2.6 on 2020-01-13 13:57

from django.db import migrations, models
import weather.models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', weather.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='favorite_cities',
            field=models.CharField(blank=True, max_length=4000),
        ),
    ]
