# Generated by Django 2.2.6 on 2020-01-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_city_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_city',
            field=models.IntegerField(default=0),
        ),
    ]
