# Generated by Django 2.2.6 on 2020-01-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_city_city_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city_city',
        ),
    ]
