# Generated by Django 2.2.6 on 2020-01-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_remove_city_city_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='API_NAME',
            field=models.CharField(default='', max_length=4000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='ERROR',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
