# Generated by Django 2.2.6 on 2020-01-14 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_auto_20200113_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='city_id',
        ),
    ]
