# Generated by Django 2.2.6 on 2020-01-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_remove_weather_city_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='date_of_getting',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
